package com.revature.drivers;

import com.revature.models.User;
import com.revature.dao.GenericDao;
import com.revature.repositories.UserPostgres;

import java.util.List;

public class JdbcDriver {
    public static void main(String[] args) {
        GenericDao<User> us = new UserPostgres();

        List<User> usrs = us.getAll();
        for (User u : usrs) {
            System.out.println(u);
        }

        System.out.println("Get userById 3:" + us.getByID(3));

        User newUser = new User(4, "test_first_name", "test_last_name", "test_username", "test_password", "test_email", 4, true);
        //saving the id generated by the database
        User idNewUsr = us.add(newUser);
        System.out.println("Generated id was: " + idNewUsr);

        //delete employee at id idNewEmp and return the number of rows changed
        System.out.println("Deleted columns: " + us.remove(idNewUsr));


        User newUsr2 = new User(4, "test_first_name", "test_last_name", "test_username", "test_password", "test_email", 4, true);

        System.out.println("Update successfully: " + us.update(newUsr2));
    }
}
